# -*- coding: utf-8 -*-
"""Augmentation.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YtX4c6BM5oDRBlFZHEndlusbuAoVtcjT
"""

import cv2
import matplotlib.pyplot as plt
import numpy as np

from google.colab import drive
drive.mount('/content/drive')

def BlurAugmentation(folder, files):
  path = folder + "/" + files
  img = cv2.imread(path,cv2.COLOR_BGR2RGB)
  blur = cv2.GaussianBlur(img, (7, 7), 3)
  cv2.imwrite(folder + "/" + "blur-" +files, blur)

def GreyAugmentation(folder, files):
  path = folder + "/" + files
  img = cv2.imread(path,cv2.COLOR_BGR2RGB)
  decolor = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY )
  cv2.imwrite(folder + "/" + "grey-" +files, decolor)

def NoiseAugmentation(folder, files):
  path = folder + "/" + files
  img = cv2.imread(path,cv2.COLOR_BGR2RGB)
  noise_img = random_noise(img, mode='s&p',amount=0.1)
  noise_img = np.array(255*noise_img, dtype = 'uint8')
  cv2.imwrite(folder + "/" + "noise-" + files, noise_img)

def BrightAugmentation(folder, files):
  path = folder + "/" + files
  img = cv2.imread(path,cv2.COLOR_BGR2RGB)
  hsv = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)
  h, s, v = cv2.split(hsv)
  value = 150
  lim = 255 - value
  v[v > lim] = 255
  v[v <= lim] += value
  final_hsv = cv2.merge((h, s, v))
  bright = cv2.cvtColor(final_hsv, cv2.COLOR_HSV2BGR)
  cv2.imwrite(folder + "/" + "bright-" + files, bright)

import os
directory = "/content/drive/MyDrive/img_celeba/subset train"
traindict = list(os.listdir(directory))

for folder in traindict:
  folderDirect = os.path.join(directory,folder)
  if os.path.isdir(folderDirect):

    for files in os.listdir(folderDirect):
      if files.find("-") == -1:
        BlurAugmentation(folderDirect,files)
        GreyAugmentation(folderDirect,files)
        NoiseAugmentation(folderDirect,files)
        BrightAugmentation(folderDirect,files)

